version: "3"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.2.1
    container_name: elasticsearch
    ports:
      - "127.0.0.1:9200:9200"
    volumes:
      - ./elasticsearch/config:/usr/share/elasticsearch/config
      - ./elasticsearch/data:/usr/share/elasticsearch/data
      - ./elasticsearch/log:/var/logs
    environment:
      SERVER_NAME: elasticsearch
      HTTP_HOST: "0.0.0.0"
      TRANSPORT_HOST: "0.0.0.0"