version: "3"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.2.1
    container_name: elasticsearch
    ports:
      - "127.0.0.1:9200:9200"
    volumes:
      - ./elasticsearch/config:/usr/share/elasticsearch/config
      - ./elasticsearch/data:/usr/share/elasticsearch/data
      - ./elasticsearch/log:/var/logs
    environment:
      SERVER_NAME: elasticsearch
      HTTP_HOST: "0.0.0.0"
      TRANSPORT_HOST: "0.0.0.0"

  logstash:
    image: docker.elastic.co/logstash/logstash:5.2.1
    container_name: logstash
    depends_on:
      - elasticsearch
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    depends_on:
      - elasticsearch
    links:
      - elasticsearch:elasticsearch
    entrypoint:
      - logstash
      - -f
      - /usr/share/logstash/pipeline/applog-pipeline.conf
      - --config.reload.automatic

  kibana:
    image: docker.elastic.co/kibana/kibana:5.2.1
    container_name: kibana
    depends_on:
      - logstash
    ports:
      - "5601:5601"
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
    links:
      - elasticsearch:elasticsearch

  filebeat:
    image: prima/filebeat:5.2.1
    container_name: filebeat
    depends_on:
      - kibana
    links:
      - logstash:logstash
    volumes:
      - ./filebeat/config/filebeat.yml:/filebeat.yml
      - ./filebeat/data:/data
      - ./tutorialLog:/serverlogs
    entrypoint:
      - filebeat
      - -e
      - -d
      - "publish"
